---
- name: install required base packages
  yum: name={{ item }}
  state: present
  with_items:
    - net-tools
    - python
    - python-setuptools

- name: install pip
  easy_install:
    name: pip
    state: present
